<?php 
/* 	
If you see this text in your browser, PHP is not configured correctly on this hosting provider. 
Contact your hosting provider regarding PHP configuration for your site.

PHP file generated by Adobe Muse CC 2014.2.1.284
*/

require_once('form_process.php');

$form = array(
	'subject' => 'Envoi de E-mail Site Web !',
	'heading' => 'Envoi du nouveau formulaire',
	'success_redirect' => 'index.html',
	'resources' => array(
		'checkbox_checked' => 'Cochée',
		'checkbox_unchecked' => 'Non cochée',
		'submitted_from' => 'Formulaire envoyé depuis le site Web :%s',
		'submitted_by' => 'Adresse IP du visiteur :%s',
		'too_many_submissions' => 'Trop d\'envois effectués récemment à partir de cette adresse IP',
		'failed_to_send_email' => 'Echec de l\'envoi du courrier électronique',
		'invalid_reCAPTCHA_private_key' => 'Clé privée reCAPTCHA non valide',
		'invalid_field_type' => 'Type de champ inconnu « %s »',
		'unknown_method' => 'Méthode de requête inconnue du serveur'
	),
	'email' => array(
		'from' => 'info@wakwhite.be',
		'to' => 'info@wakwhite.be'
	),
	'fields' => array(
		'custom_U547' => array(
			'type' => 'string',
			'label' => 'NOM',
			'required' => true,
			'errors' => array(
				'required' => 'Le champ « NOM » est obligatoire.'
			)
		),
		'Email' => array(
			'type' => 'email',
			'label' => 'E-MAIL',
			'required' => true,
			'errors' => array(
				'required' => 'Le champ « E-MAIL » est obligatoire.',
				'format' => 'Le champ « E-MAIL » contient une adresse électronique non valide.'
			)
		),
		'custom_U555' => array(
			'type' => 'string',
			'label' => 'MESSAGE',
			'required' => false,
			'errors' => array(
			)
		),
		'custom_U541' => array(
			'type' => 'string',
			'label' => 'OBJET',
			'required' => false,
			'errors' => array(
			)
		)
	)
);

process_form($form);
?>
